name: Set up Traefik and PHP container on EC2

on:
  workflow_run:
    workflows: [ "Install Docker and Docker Compose on EC2" ]
    types:
    - completed

jobs:
  setup_traefik_php:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Copying docker-compose to EC2
      run: |
        
        # Copy traefik docker-compose.yml to EC2
        echo "Copying Traefik docker-compose.yml..."
        scp -r -o StrictHostKeyChecking=no ./docker ubuntu@${{ secrets.EC2_IP_ADDRESS }}:~

    - name: Upload and deploy Traefik and PHP containers to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP_ADDRESS }} << 'EOF'

          # Start the containers
          cd ~/docker
          docker-compose up -d

        EOF
